# app/utils/_constants.py
"""
System-wide constants and configuration values.
"""

# Task Status Values
TASK_STATUS_PENDING = "pending"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_DONE = "done"
TASK_STATUS_BLOCKED = "blocked"
TASK_STATUS_DELAYED = "delayed"

TASK_STATUSES = [
    TASK_STATUS_PENDING,
    TASK_STATUS_RUNNING,
    TASK_STATUS_DONE,
    TASK_STATUS_BLOCKED,
    TASK_STATUS_DELAYED
]

# Project Status Values
PROJECT_STATUS_PLANNING = "planning"
PROJECT_STATUS_IN_PROGRESS = "in-progress"
PROJECT_STATUS_ON_HOLD = "on-hold"
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_CANCELLED = "cancelled"

PROJECT_STATUSES = [
    PROJECT_STATUS_PLANNING,
    PROJECT_STATUS_IN_PROGRESS,
    PROJECT_STATUS_ON_HOLD,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_CANCELLED
]

# Priority Levels
PRIORITY_LOW = "low"
PRIORITY_MEDIUM = "medium"
PRIORITY_HIGH = "high"
PRIORITY_CRITICAL = "critical"

PRIORITY_LEVELS = [PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_HIGH, PRIORITY_CRITICAL]

# Difficulty Levels
DIFFICULTY_EASY = "easy"
DIFFICULTY_MEDIUM = "medium"
DIFFICULTY_HARD = "hard"

DIFFICULTY_LEVELS = [DIFFICULTY_EASY, DIFFICULTY_MEDIUM, DIFFICULTY_HARD]

# Urgency Levels
URGENCY_LOW = "low"
URGENCY_MEDIUM = "medium"
URGENCY_HIGH = "high"
URGENCY_CRITICAL = "critical"

URGENCY_LEVELS = [URGENCY_LOW, URGENCY_MEDIUM, URGENCY_HIGH, URGENCY_CRITICAL]

# Blocker Types
BLOCKER_TYPE_DEPENDENCY = "dependency"
BLOCKER_TYPE_RESOURCE = "resource"
BLOCKER_TYPE_EXTERNAL = "external"
BLOCKER_TYPE_AMBIGUITY = "ambiguity"

# Blocker Severity
BLOCKER_SEVERITY_LOW = "low"
BLOCKER_SEVERITY_MEDIUM = "medium"
BLOCKER_SEVERITY_HIGH = "high"
BLOCKER_SEVERITY_CRITICAL = "critical"

# Blocker Status
BLOCKER_STATUS_OPEN = "open"
BLOCKER_STATUS_IN_PROGRESS = "in-progress"
BLOCKER_STATUS_RESOLVED = "resolved"
BLOCKER_STATUS_ESCALATED = "escalated"

# Decision Types
DECISION_TYPE_ASSIGNMENT = "assignment"
DECISION_TYPE_REASSIGNMENT = "reassignment"
DECISION_TYPE_DEADLINE_CHANGE = "deadline_change"
DECISION_TYPE_REBALANCE = "rebalance"
DECISION_TYPE_ESCALATION = "escalation"

# Event Types
EVENT_TYPE_TASK_CREATED = "TASK_CREATED"
EVENT_TYPE_TASK_UPDATED = "TASK_UPDATED"
EVENT_TYPE_PROJECT_CREATED = "PROJECT_CREATED"
EVENT_TYPE_ASSIGNMENT_COMPLETE = "ASSIGNMENT_COMPLETE"
EVENT_TYPE_BLOCKER_DETECTED = "BLOCKER_DETECTED"
EVENT_TYPE_REBALANCE_NEEDED = "REBALANCE_NEEDED"

# Assignment Engine Weights
ASSIGNMENT_WEIGHT_SKILL_MATCH = 0.35
ASSIGNMENT_WEIGHT_WORKLOAD = 0.25
ASSIGNMENT_WEIGHT_EFFICIENCY = 0.20
ASSIGNMENT_WEIGHT_RELIABILITY = 0.20

# Thresholds
MIN_ASSIGNMENT_CONFIDENCE = 0.5
OVERLOAD_THRESHOLD = 0.9  # 90% capacity
DELAY_RISK_THRESHOLD = 0.5

# User Roles
ROLE_PLATFORM_OWNER = "platform_owner"
ROLE_CEO = "ceo"
ROLE_ADMIN = "admin"
ROLE_EMPLOYEE = "employee"
ROLE_CLIENT = "client"

USER_ROLES = [ROLE_PLATFORM_OWNER, ROLE_CEO, ROLE_ADMIN, ROLE_EMPLOYEE, ROLE_CLIENT]
ROLES = USER_ROLES

# Availability Status
AVAILABILITY_AVAILABLE = "available"
AVAILABILITY_ON_LEAVE = "on-leave"
AVAILABILITY_BUSY = "busy"

# Meeting Types
MEETING_TYPE_STATUS = "status"
MEETING_TYPE_EMERGENCY = "emergency"
MEETING_TYPE_REVIEW = "review"
MEETING_TYPE_PLANNING = "planning"

# Risk Levels
RISK_LEVEL_LOW = "low"
RISK_LEVEL_MEDIUM = "medium"
RISK_LEVEL_HIGH = "high"
RISK_LEVEL_CRITICAL = "critical"

# Payment Status
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PARTIAL = "partial"
PAYMENT_STATUS_COMPLETED = "completed"
