"""
Platform Assistant — ManH, the AI assistant for all roles.
Fully LLM-powered with live DB context and conversation history.
"""
from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.core._deps import get_current_user, get_db
from app.models._user import User

router = APIRouter(tags=["Assistant"])

# ── Platform knowledge injected into every LLM call ─────────────────────────

PLATFORM_OVERVIEW = """
AI Workforce Orchestrator is a multi-tenant B2B SaaS platform that uses
AI agents (Google ADK + Gemini 2.5 Flash via Vertex AI) to automate workforce
management, project delivery, task assignment, risk assessment, and client
communication.

ROLES & WHAT THEY CAN DO:
- platform_owner: Manages all companies (tenants) on the platform. Can suspend/
  activate companies, respond to support tickets, view platform-wide metrics and MRR.
- ceo: Strategic oversight of their company. Sees company-wide health, financial
  overview, AI-generated risk flags, project portfolio, team performance. Has 2FA.
- admin: Runs day-to-day operations. Creates/manages projects and tasks, assigns
  employees, triggers AI agent workflows, views decision logs and audit trail.
- employee: Views and works on assigned tasks, updates task progress, sees their
  workload and projects.
- client: Views the status of their projects, sees progress updates and
  communications from the team.

KEY FEATURES:
- Projects: Create projects with budget, deadline, priority, client association.
- Tasks: Each project has tasks with required skills, urgency, difficulty, status.
- AI Task Assignment: StaffingAgent scores and assigns employees by skill match,
  workload, and efficiency rating.
- Multi-Agent Workbench: Trigger the full intake pipeline (IntakeAgent →
  PlanningAgent → StaffingAgent → RiskAgent → ExecutionCoordinator →
  CommunicationAgent → EscalationAgent).
- CEO Dashboard: Company overview, financial summary, active risk flags, team stats.
- Billing: Subscription plans — Trial (free/30d), Starter (₹1,000/mo),
  Pro (₹5,000/6mo), Enterprise (₹15,000/yr). Grace period before auto-suspend.
- Settings: Profile (avatar, name, email, phone, position, location), security
  (change password, 2FA), preferences (theme, timezone, notifications).
- Support: Any user can raise a support ticket; platform owner responds.
- Google Calendar: Admins and CEOs can connect Google Calendar for meeting sync.

NAVIGATION:
- platform_owner → Owner Panel (tenant list, support inbox)
- ceo → CEO Dashboard, Projects
- admin → Admin Dashboard, Projects, Team Dashboard, Agentic Dashboard, Multi-Agent
- employee → My Dashboard, My Projects, My Work
- client → Client Dashboard, Project Status
- All roles: Settings (avatar icon top-right)
"""

ROLE_NAV: dict[str, str] = {
    "platform_owner": "Owner Panel (tenant list, metrics, support inbox), Settings",
    "ceo": "CEO Dashboard, Projects, Settings",
    "admin": "Admin Dashboard, Projects, Team Dashboard, Agentic Dashboard, Multi-Agent Workbench, Settings",
    "employee": "My Dashboard, My Projects, My Work, Settings",
    "client": "Client Dashboard, Project Status, Settings",
}

# kept for the onboarding endpoint only
ROLE_TIPS: dict[str, list[str]] = {
    "platform_owner": [
        "Use the Owner Panel to see all registered companies and their plan status.",
        "Click ⏸ Suspend to lock out a company — their admins get an automatic email.",
        "Respond to support tickets in the Support Inbox — replies go to the user's email.",
        "The MRR estimate at the top is calculated from all active paid subscriptions.",
        "Companies in Grace Period will auto-suspend when the countdown hits zero.",
    ],
    "ceo": [
        "The CEO Dashboard shows your company's health score, active risks, and financials.",
        "Risk flags are generated by the AI RiskAgent — red = critical, amber = high.",
        "Enable 2FA in Settings → Security for extra account protection.",
        "You can connect Google Calendar in Settings → Integrations to sync meetings.",
        "Use the Project view to drill into any project's task breakdown and team.",
    ],
    "admin": [
        "Create a project in Projects → New Project, then add tasks with required skills.",
        "The Multi-Agent Workbench lets you trigger the full AI intake pipeline for a project.",
        "The Agentic Dashboard shows every AI decision with confidence scores and reasoning.",
        "Task Assignment is scored automatically — you can also assign manually.",
        "Blockers on tasks automatically flag risk in the RiskAgent's next run.",
    ],
    "employee": [
        "Your Dashboard shows tasks assigned to you, sorted by urgency.",
        "Update task progress in My Work to keep your workload accurate.",
        "Your skills profile affects which tasks the AI assigns to you — keep it updated.",
        "If a task is blocked, flag it so admins and the AI can reassign or escalate.",
    ],
    "client": [
        "Project Status shows real-time progress of your projects.",
        "Task completion percentage updates as the team marks tasks done.",
        "Contact your admin if you need to change project scope or deadlines.",
    ],
}

# ── Keyword fallback ──────────────────────────────────────────────────────────

# Role-specific keyword answers checked first (before generic ones)
# ── LLM-powered chat endpoint ─────────────────────────────────────────────────

class ChatMessage(BaseModel):
    role: str   # "user" | "assistant"
    text: str


class AssistantRequest(BaseModel):
    message: str = Field(min_length=1, max_length=2000)
    history: list[ChatMessage] = []


class AssistantResponse(BaseModel):
    reply: str
    source: str   # "llm" | "unavailable"


@router.post("/chat", response_model=AssistantResponse)
def assistant_chat(
    payload: AssistantRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    from app.services._assistant_context import build_context
    from app.services._llm_service import LLMService

    message = payload.message.strip()
    role    = current_user.role
    name    = current_user.full_name or current_user.email.split("@")[0]

    live_context = build_context(db, current_user)

    try:
        llm = LLMService()
        if not llm.enabled:
            raise RuntimeError("LLM not configured")

        # Build conversation history for multi-turn context
        history_text = ""
        if payload.history:
            history_lines = []
            for msg in payload.history[-10:]:   # last 10 turns
                prefix = "User" if msg.role == "user" else "ManH"
                history_lines.append(f"{prefix}: {msg.text}")
            history_text = "\n".join(history_lines) + "\n"

        full_message = f"{history_text}User: {message}" if history_text else message

        reply = llm.answer_user_question(
            message=full_message,
            role=role,
            user_name=name,
            live_context=live_context,
            platform_overview=PLATFORM_OVERVIEW,
        )
        return AssistantResponse(reply=reply, source="llm")

    except Exception:
        nav = ROLE_NAV.get(role, "the platform")
        return AssistantResponse(
            reply=(
                f"I'm having trouble connecting to the AI right now. "
                f"As a {role.replace('_', ' ')}, your main pages are: {nav}. "
                "Try again in a moment, or raise a support ticket in Settings → Support."
            ),
            source="unavailable",
        )


# ── Natural Language Query endpoint ──────────────────────────────────────────

class NLQueryRequest(BaseModel):
    question: str = Field(min_length=3, max_length=500)


class NLQueryResponse(BaseModel):
    answer: str
    data: dict
    source: str  # "llm" | "structured"


def _gather_live_data(db: Session, current_user: User, question: str) -> dict:
    """Pull relevant DB facts based on question keywords."""
    from app.models._employee_profile import EmployeeProfile
    from app.models._project import Project
    from app.models._task import Task
    from app.models._task_assignment import TaskAssignment
    from app.models._blocker import Blocker

    lower = question.lower()
    tid = current_user.tenant_id
    data: dict = {}

    if any(w in lower for w in ("capacity", "available", "free", "bandwidth", "load", "workload", "who")):
        employees = db.query(EmployeeProfile).filter(EmployeeProfile.tenant_id == tid).all()
        data["team"] = [
            {
                "name": (e.user.full_name or e.user.email) if e.user else str(e.id),
                "current_load": e.current_load,
                "max_capacity": e.max_capacity,
                "free_hours": round(max(0.0, (e.max_capacity or 8) - (e.current_load or 0)), 1),
                "status": e.availability_status,
            }
            for e in employees
        ]

    if any(w in lower for w in ("project", "risk", "behind", "overdue", "status", "progress", "at risk")):
        projects = db.query(Project).filter(Project.tenant_id == tid).all()
        data["projects"] = [
            {
                "name": p.name,
                "status": p.status,
                "progress": p.progress,
                "priority": p.priority,
                "budget": p.budget,
                "spent": p.spent,
            }
            for p in projects
        ]

    if any(w in lower for w in ("task", "done", "complet", "pending", "blocked", "assign")):
        tasks = db.query(Task).filter(Task.tenant_id == tid).all()
        status_counts: dict = {}
        for t in tasks:
            status_counts[t.status] = status_counts.get(t.status, 0) + 1
        data["task_summary"] = status_counts

    if any(w in lower for w in ("block", "stuck", "impediment")):
        blockers = db.query(Blocker).filter(Blocker.tenant_id == tid, Blocker.resolved == False).all()
        data["active_blockers"] = len(blockers)

    return data


def _format_structured_answer(question: str, data: dict) -> str:
    lower = question.lower()
    parts = []

    if "team" in data:
        team = data["team"]
        available = [e for e in team if e["free_hours"] > 0]
        overloaded = [e for e in team if e["free_hours"] <= 0]
        if any(w in lower for w in ("capacity", "available", "free", "bandwidth")):
            if available:
                parts.append(
                    "**Available team members:**\n" +
                    "\n".join(f"- {e['name']}: {e['free_hours']}h free ({e['status']})" for e in available)
                )
            else:
                parts.append("No team members currently have free capacity.")
        elif any(w in lower for w in ("load", "workload", "busy")):
            if overloaded:
                parts.append(
                    "**Overloaded members:**\n" +
                    "\n".join(f"- {e['name']}: {e['current_load']}h load / {e['max_capacity']}h capacity" for e in overloaded)
                )
            parts.append(
                "**Team load overview:**\n" +
                "\n".join(f"- {e['name']}: {e['current_load']}/{e['max_capacity']}h" for e in team)
            )

    if "projects" in data:
        projects = data["projects"]
        if any(w in lower for w in ("risk", "at risk")):
            risky = [p for p in projects if p.get("status") in ("delayed", "at-risk") or (p.get("priority") == "critical" and p.get("progress", 100) < 50)]
            parts.append(
                f"**{len(risky)} project(s) may be at risk:**\n" +
                ("\n".join(f"- {p['name']} ({p['status']}, {p['progress']}% complete)" for p in risky) if risky else "None flagged currently.")
            )
        else:
            parts.append(
                f"**{len(projects)} project(s):**\n" +
                "\n".join(f"- {p['name']}: {p['status']} ({p['progress']}%)" for p in projects[:8])
            )

    if "task_summary" in data:
        ts = data["task_summary"]
        parts.append(
            "**Task breakdown:** " +
            ", ".join(f"{v} {k}" for k, v in ts.items())
        )

    if "active_blockers" in data:
        parts.append(f"**Active blockers:** {data['active_blockers']}")

    return "\n\n".join(parts) if parts else "I don't have enough live data to answer that question yet."


@router.post("/nl-query", response_model=NLQueryResponse)
def nl_query(
    payload: NLQueryRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Answer a natural language question using live DB data. Admin/CEO only."""
    if current_user.role not in ("admin", "ceo", "platform_owner"):
        from fastapi import HTTPException
        raise HTTPException(status_code=403, detail="Only admins and CEOs can run live queries")

    question = payload.question.strip()
    live_data = _gather_live_data(db, current_user, question)

    # Try LLM with live data as context
    try:
        from app.services._llm_service import LLMService
        llm = LLMService()
        if llm.enabled:
            context_str = f"Live platform data:\n{live_data}\n\nUser question: {question}"
            answer = llm.answer_user_question(
                message=context_str,
                role=current_user.role,
                user_name=current_user.full_name or current_user.email,
                live_context="",
                platform_overview=PLATFORM_OVERVIEW,
            )
            if answer:
                return NLQueryResponse(answer=answer, data=live_data, source="llm")
    except Exception:
        pass

    # Fallback: structured answer from data
    answer = _format_structured_answer(question, live_data)
    return NLQueryResponse(answer=answer, data=live_data, source="structured")


@router.get("/onboarding-steps")
def get_onboarding_steps(current_user: User = Depends(get_current_user)):
    """Return role-specific onboarding steps."""
    role = current_user.role
    steps: list[dict[str, Any]] = {
        "platform_owner": [
            {"title": "Welcome, Platform Owner 👋", "body": "You have god-level access to the entire platform. You can see all companies, manage their subscriptions, and respond to support tickets — but you cannot see inside their data.", "icon": "🏛", "page": None},
            {"title": "Company Directory", "body": "The Owner Panel shows every registered company with their plan, user count, project count, and billing status. Companies in Grace Period will auto-suspend when the countdown hits zero.", "icon": "🏢", "page": "owner"},
            {"title": "Suspend & Activate", "body": "Use the ⏸ Suspend button to lock out a company instantly — their admins get an email. The button flips to ▶ Activate when suspended. Suspension requires a reason.", "icon": "⏸", "page": "owner"},
            {"title": "Support Inbox", "body": "When any admin or CEO raises a support ticket, it lands here. Type your response and hit Send — the user gets an email reply and the ticket resolves.", "icon": "📬", "page": "owner"},
            {"title": "Platform Metrics", "body": "The top bar shows total tenants, active vs suspended, trial vs paid, and estimated MRR in ₹ — calculated from all live subscriptions.", "icon": "📊", "page": "owner"},
            {"title": "Your Profile", "body": "Set up your profile in Settings → Profile. Upload a photo, add your position (Founder / CEO work great here), and set your timezone.", "icon": "👤", "page": "settings"},
        ],
        "ceo": [
            {"title": "Welcome to your command centre 👋", "body": "As CEO you have strategic oversight of your entire company. You can see health scores, financial data, AI risk flags, and drill into any project — all in one place.", "icon": "📈", "page": None},
            {"title": "CEO Dashboard", "body": "Your landing page shows company health, active projects, tasks in flight, team efficiency, and total budget vs spent. Everything updates in real time.", "icon": "🎯", "page": "ceo"},
            {"title": "AI Risk Flags", "body": "The RiskAgent continuously monitors all projects and surfaces risks with severity ratings. Red = critical, orange = high. Click any flag to see the AI's reasoning.", "icon": "⚠️", "page": "ceo"},
            {"title": "Financial Overview", "body": "See total budget allocated, amount spent, outstanding invoices, and payment status across all projects in your company.", "icon": "💰", "page": "ceo"},
            {"title": "2FA is protecting you", "body": "Your account is secured with two-factor authentication. You need your authenticator app each time you log in. You can manage 2FA in Settings → Security.", "icon": "🔐", "page": "settings"},
            {"title": "Google Calendar sync", "body": "Connect your Google Calendar in Settings → Integrations so platform meetings sync automatically to your calendar.", "icon": "📅", "page": "settings"},
        ],
        "admin": [
            {"title": "Welcome, Admin 👋", "body": "You run day-to-day operations. You can create and manage projects, assign employees, trigger AI agent workflows, and see every AI decision your system makes.", "icon": "⚙️", "page": None},
            {"title": "Projects", "body": "Create a project with a budget, deadline, priority, and client. Then add tasks with required skills — the AI will handle staffing automatically.", "icon": "📁", "page": "projects"},
            {"title": "Team Dashboard", "body": "See all your employees, their skills, current workload, and availability. The AI uses this data to make assignment decisions.", "icon": "👥", "page": "employees"},
            {"title": "Multi-Agent Workbench", "body": "Trigger the full AI pipeline for any project. Seven agents run in sequence: Intake → Planning → Staffing → Risk → Execution → Communication → Escalation.", "icon": "🤖", "page": "multi-agent"},
            {"title": "Agentic Dashboard", "body": "See every decision the AI has made — with confidence scores, reasoning, and input/output data. Full transparency and audit trail.", "icon": "🧠", "page": "decisions"},
            {"title": "Your Profile & Settings", "body": "Set up your profile, connect Google Calendar, configure email notifications, and manage your password in Settings.", "icon": "👤", "page": "settings"},
        ],
        "employee": [
            {"title": "Welcome to your workspace 👋", "body": "The AI assigns tasks to you based on your skills, current workload, and efficiency score. Keep your profile updated to get the best matches.", "icon": "🧑‍💻", "page": None},
            {"title": "My Dashboard", "body": "Your dashboard shows all tasks assigned to you, sorted by urgency. You can see deadlines, required skills, and the project each task belongs to.", "icon": "📋", "page": "dashboard"},
            {"title": "Task Progress", "body": "Click any task to update its progress, add notes, or flag it as blocked. Blocked tasks trigger the AI EscalationAgent automatically.", "icon": "✅", "page": "dashboard"},
            {"title": "My Projects", "body": "See all projects you are involved in, your role on each, and the overall project health and progress.", "icon": "📁", "page": "projects"},
            {"title": "Your Profile & Skills", "body": "Update your skills in Settings → Profile. The AI StaffingAgent uses your skills profile to score task-to-employee fit — higher scores mean better matches.", "icon": "🎯", "page": "settings"},
        ],
        "client": [
            {"title": "Welcome 👋", "body": "This is your project portal. You can see the real-time status of your projects, task progress, and receive updates from the team — all in one place.", "icon": "👁", "page": None},
            {"title": "Project Status", "body": "The Projects page shows all your active projects with progress bars, budget usage, priority, and current status. Click any project to drill in.", "icon": "📊", "page": "projects"},
            {"title": "Task Progress", "body": "Inside each project you can see individual tasks, their completion status, and which team member is working on them.", "icon": "✅", "page": "projects"},
            {"title": "Getting help", "body": "If you need to raise a concern or request a change, use Settings → Support to send a message directly to your team's admin.", "icon": "💬", "page": "settings"},
        ],
    }.get(role, [
        {"title": "Welcome to AI Workforce Orchestrator", "body": "Use the navigation bar to explore your available features.", "icon": "👋", "page": None},
    ])

    return {"role": role, "steps": steps}
