"""
Platform Assistant — intelligent helper for all roles.
Answers questions about the platform, guides users through features,
and helps with workflows. LLM-powered with keyword fallback.
"""
from __future__ import annotations

import re
from typing import Any

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from app.core._deps import get_current_user
from app.models._user import User

router = APIRouter(tags=["Assistant"])

# ── Role-aware platform knowledge base ───────────────────────────────────────

PLATFORM_OVERVIEW = """
AI Workforce Orchestrator is a multi-tenant B2B SaaS platform that uses
AI agents (Google ADK + Gemini 2.5 Flash via Vertex AI) to automate workforce
management, project delivery, task assignment, risk assessment, and client
communication.

ROLES & WHAT THEY CAN DO:
- platform_owner: Manages all companies (tenants) on the platform. Can suspend/
  activate companies, respond to support tickets, view platform-wide metrics and MRR.
- ceo: Strategic oversight of their company. Sees company-wide health, financial
  overview, AI-generated risk flags, project portfolio, team performance. Has 2FA.
- admin: Runs day-to-day operations. Creates/manages projects and tasks, assigns
  employees, triggers AI agent workflows, views decision logs and audit trail.
- employee: Views and works on assigned tasks, updates task progress, sees their
  workload and projects.
- client: Views the status of their projects, sees progress updates and
  communications from the team.

KEY FEATURES:
- Projects: Create projects with budget, deadline, priority, client association.
- Tasks: Each project has tasks with required skills, urgency, difficulty, status.
- AI Task Assignment: StaffingAgent scores and assigns employees by skill match,
  workload, and efficiency rating.
- Multi-Agent Workbench: Trigger the full intake pipeline (IntakeAgent →
  PlanningAgent → StaffingAgent → RiskAgent → ExecutionCoordinator →
  CommunicationAgent → EscalationAgent).
- CEO Dashboard: Company overview, financial summary, active risk flags, team stats.
- Billing: Subscription plans — Trial (free/30d), Starter (₹1,000/mo),
  Pro (₹5,000/6mo), Enterprise (₹15,000/yr). Grace period before auto-suspend.
- Settings: Profile (avatar, name, email, phone, position, location), security
  (change password, 2FA), preferences (theme, timezone, notifications).
- Support: Any user can raise a support ticket; platform owner responds.
- Google Calendar: Admins and CEOs can connect Google Calendar for meeting sync.

NAVIGATION:
- platform_owner → Owner Panel (tenant list, support inbox)
- ceo → CEO Dashboard, Projects
- admin → Admin Dashboard, Projects, Team Dashboard, Agentic Dashboard, Multi-Agent
- employee → My Dashboard, My Projects, My Work
- client → Client Dashboard, Project Status
- All roles: Settings (avatar icon top-right)
"""

ROLE_TIPS: dict[str, list[str]] = {
    "platform_owner": [
        "Use the Owner Panel to see all registered companies and their plan status.",
        "Click ⏸ Suspend to lock out a company — their admins get an automatic email.",
        "Respond to support tickets in the Support Inbox — replies go to the user's email.",
        "The MRR estimate at the top is calculated from all active paid subscriptions.",
        "Companies in Grace Period will auto-suspend when the countdown hits zero.",
    ],
    "ceo": [
        "The CEO Dashboard shows your company's health score, active risks, and financials.",
        "Risk flags are generated by the AI RiskAgent — red = critical, amber = high.",
        "Enable 2FA in Settings → Security for extra account protection.",
        "You can connect Google Calendar in Settings → Integrations to sync meetings.",
        "Use the Project view to drill into any project's task breakdown and team.",
    ],
    "admin": [
        "Create a project in Projects → New Project, then add tasks with required skills.",
        "The Multi-Agent Workbench lets you trigger the full AI intake pipeline for a project.",
        "The Agentic Dashboard shows every AI decision with confidence scores and reasoning.",
        "Task Assignment is scored automatically — you can also assign manually.",
        "Blockers on tasks automatically flag risk in the RiskAgent's next run.",
    ],
    "employee": [
        "Your Dashboard shows tasks assigned to you, sorted by urgency.",
        "Update task progress in My Work to keep your workload accurate.",
        "Your skills profile affects which tasks the AI assigns to you — keep it updated.",
        "If a task is blocked, flag it so admins and the AI can reassign or escalate.",
    ],
    "client": [
        "Project Status shows real-time progress of your projects.",
        "Task completion percentage updates as the team marks tasks done.",
        "Contact your admin if you need to change project scope or deadlines.",
    ],
}

# ── Keyword fallback ──────────────────────────────────────────────────────────

# Role-specific keyword answers checked first (before generic ones)
ROLE_KEYWORD_ANSWERS: dict[str, list[tuple[list[str], str]]] = {
    "platform_owner": [
        (["subscription", "active", "expire", "expir", "billing status", "account status",
          "check account", "check company", "is active", "still active", "grace", "trial period",
          "when does", "how long", "days left", "time left", "renewal"],
         "Go to the Owner Panel (top nav). Each company card shows its billing status badge — "
         "Active (green), Expiring Soon (amber, ≤7 days), Grace Period (orange, auto-suspend countdown), "
         "Expired (red), or Suspended. The card also shows the plan name, exact expiry date, and how many "
         "days remain. A ⚠ banner appears when a company is in its grace window and will auto-suspend soon."),
        (["mrr", "revenue", "how much", "total revenue", "platform revenue"],
         "The Owner Panel top bar shows an MRR estimate calculated from all active paid subscriptions across every tenant. "
         "Trial companies contribute ₹0; Starter ₹1,000/mo; Pro ₹833/mo (₹5,000/6mo); Enterprise ₹1,250/mo (₹15,000/yr)."),
        (["all companies", "list companies", "how many companies", "all tenants", "list tenants", "see all"],
         "The Owner Panel lists every registered company with their plan, user count, project count, billing status, "
         "and subscription dates. Use the search bar at the top to filter by name."),
    ],
    "ceo": [
        (["subscription", "billing", "plan", "payment", "upgrade"],
         "Your company's subscription is managed by your admin. View your current plan and billing status in Settings → Billing. "
         "To upgrade, contact your platform owner or go to Settings → Billing → Upgrade Plan."),
    ],
    "admin": [
        (["subscription", "billing", "plan", "payment", "upgrade"],
         "Manage your company's subscription in Settings → Billing. You can see your current plan, expiry date, "
         "and upgrade to Starter, Pro, or Enterprise from there."),
    ],
}

KEYWORD_ANSWERS: list[tuple[list[str], str]] = [
    (["suspend", "lock", "deactivate", "block company"],
     "To suspend a company: go to Owner Panel → find the company → click ⏸ Suspend. Enter the reason. The company's users are locked out immediately and the admin receives an email."),
    (["activate", "reactivate", "unsuspend"],
     "To reactivate a company: go to Owner Panel → find the suspended company (red border) → click ▶ Activate. Access is restored immediately."),
    (["support ticket", "raise ticket", "help ticket", "ticket"],
     "To raise a support ticket: go to Settings → Support tab → fill in the subject and body → Submit. The platform owner will reply to your email."),
    (["password", "change password", "reset password"],
     "Go to Settings → Security tab. Enter your current password, then your new password twice. Click Change Password. Passwords must be at least 8 characters."),
    (["2fa", "two factor", "totp", "authenticator"],
     "2FA is available in Settings → Security. Scan the QR code with Google Authenticator or Authy, then enter the 6-digit code to enable. CEOs have 2FA enabled by default."),
    (["profile", "avatar", "photo", "picture", "name"],
     "Go to Settings → Profile. Click ✏ Edit to update your name, photo, position, location, phone, or secondary email. Click your avatar circle to upload a photo (max 2 MB)."),
    (["project", "create project", "new project"],
     "Admins: go to Projects → New Project. Fill in name, description, budget, deadline, priority, and client. Once created, add tasks to it."),
    (["task", "assign task", "create task"],
     "Tasks belong to projects. Open a project → Add Task. Set required skills, urgency, difficulty, and estimated hours. The AI StaffingAgent will score and assign the best-matched employee automatically."),
    (["agent", "ai agent", "workflow", "pipeline", "multi-agent"],
     "The Multi-Agent Workbench (admin only) lets you trigger the full AI pipeline: IntakeAgent → PlanningAgent → StaffingAgent → RiskAgent → ExecutionCoordinator → CommunicationAgent → EscalationAgent."),
    (["ceo dashboard", "company overview", "risk", "financials"],
     "The CEO Dashboard shows: company health score, active project count, risk flags (AI-generated), financial overview (budget vs spent), and team performance metrics."),
    (["billing", "plan", "subscription", "upgrade", "payment"],
     "Plans: Trial (free/30d, 1 team), Starter (₹1,000/mo, 10 teams), Pro (₹5,000/6mo, unlimited), Enterprise (₹15,000/yr, unlimited+SLA). Manage in Settings → Billing."),
    (["calendar", "google calendar", "meeting", "sync"],
     "Connect Google Calendar in Settings → Integrations. Once connected, meetings created in the platform sync to your calendar automatically."),
    (["theme", "dark mode", "light mode", "appearance"],
     "Toggle dark/light mode using the ☀/🌙 button in the top navbar. Change colour palette (Sage, Ocean, Sunset) using the Palette dropdown next to it."),
    (["navigate", "where", "find", "go to", "how do i get to"],
     "Use the top navbar to navigate. Your available pages depend on your role. You can also access Settings and Support from the avatar menu (top-right)."),
    (["tenant", "company", "organisation"],
     "Each company on the platform is a tenant. Platform owners can see all tenants in the Owner Panel. Each tenant is isolated — users and projects are never visible across companies."),
    (["onboarding", "tutorial", "guide", "getting started", "walkthrough"],
     "The onboarding wizard runs automatically on first login. You can re-run it anytime by clicking the 🎓 icon at the bottom of the screen."),
]


def _keyword_match(message: str, role: str = "") -> str | None:
    lower = message.lower()
    # Check role-specific answers first (more precise)
    for keywords, answer in ROLE_KEYWORD_ANSWERS.get(role, []):
        if any(kw in lower for kw in keywords):
            return answer
    # Fall back to generic answers
    for keywords, answer in KEYWORD_ANSWERS:
        if any(kw in lower for kw in keywords):
            return answer
    return None


# ── LLM call ─────────────────────────────────────────────────────────────────

def _llm_answer(message: str, role: str, user_name: str) -> str | None:
    try:
        from app.services._llm_service import LLMService
        from langchain_core.messages import HumanMessage, SystemMessage

        llm = LLMService()
        if not llm.enabled:
            return None

        system = (
            f"You are the intelligent assistant for AI Workforce Orchestrator, a B2B SaaS platform. "
            f"The user's name is {user_name} and their role is '{role}'. "
            f"Answer only questions about the platform features, navigation, and workflows. "
            f"Be concise (2-4 sentences max). If asked something unrelated to the platform, politely redirect. "
            f"\n\nPLATFORM KNOWLEDGE:\n{PLATFORM_OVERVIEW}"
        )
        messages = [SystemMessage(content=system), HumanMessage(content=message)]
        return llm._invoke_text(messages)
    except Exception:
        return None


# ── Endpoint ──────────────────────────────────────────────────────────────────

class AssistantRequest(BaseModel):
    message: str = Field(min_length=1, max_length=2000)


class AssistantResponse(BaseModel):
    reply: str
    source: str   # "llm" | "keyword" | "fallback"


@router.post("/chat", response_model=AssistantResponse)
def assistant_chat(
    payload: AssistantRequest,
    current_user: User = Depends(get_current_user),
):
    message  = payload.message.strip()
    role     = current_user.role
    name     = current_user.full_name or current_user.email.split("@")[0]

    # 1. Try LLM
    llm_reply = _llm_answer(message, role, name)
    if llm_reply:
        return AssistantResponse(reply=llm_reply, source="llm")

    # 2. Keyword match (role-aware)
    kw_reply = _keyword_match(message, role)
    if kw_reply:
        return AssistantResponse(reply=kw_reply, source="keyword")

    # 3. Role tips
    tips = ROLE_TIPS.get(role, [])
    tip  = tips[hash(message) % len(tips)] if tips else None
    if tip:
        return AssistantResponse(
            reply=f"I'm not sure about that specifically, but here's a tip for your role: {tip}",
            source="fallback",
        )

    return AssistantResponse(
        reply="I'm your platform assistant. Ask me anything about navigating the platform, managing projects, understanding AI agents, or your account settings.",
        source="fallback",
    )


@router.get("/onboarding-steps")
def get_onboarding_steps(current_user: User = Depends(get_current_user)):
    """Return role-specific onboarding steps."""
    role = current_user.role
    steps: list[dict[str, Any]] = {
        "platform_owner": [
            {"title": "Welcome, Platform Owner 👋", "body": "You have god-level access to the entire platform. You can see all companies, manage their subscriptions, and respond to support tickets — but you cannot see inside their data.", "icon": "🏛", "page": None},
            {"title": "Company Directory", "body": "The Owner Panel shows every registered company with their plan, user count, project count, and billing status. Companies in Grace Period will auto-suspend when the countdown hits zero.", "icon": "🏢", "page": "owner"},
            {"title": "Suspend & Activate", "body": "Use the ⏸ Suspend button to lock out a company instantly — their admins get an email. The button flips to ▶ Activate when suspended. Suspension requires a reason.", "icon": "⏸", "page": "owner"},
            {"title": "Support Inbox", "body": "When any admin or CEO raises a support ticket, it lands here. Type your response and hit Send — the user gets an email reply and the ticket resolves.", "icon": "📬", "page": "owner"},
            {"title": "Platform Metrics", "body": "The top bar shows total tenants, active vs suspended, trial vs paid, and estimated MRR in ₹ — calculated from all live subscriptions.", "icon": "📊", "page": "owner"},
            {"title": "Your Profile", "body": "Set up your profile in Settings → Profile. Upload a photo, add your position (Founder / CEO work great here), and set your timezone.", "icon": "👤", "page": "settings"},
        ],
        "ceo": [
            {"title": "Welcome to your command centre 👋", "body": "As CEO you have strategic oversight of your entire company. You can see health scores, financial data, AI risk flags, and drill into any project — all in one place.", "icon": "📈", "page": None},
            {"title": "CEO Dashboard", "body": "Your landing page shows company health, active projects, tasks in flight, team efficiency, and total budget vs spent. Everything updates in real time.", "icon": "🎯", "page": "ceo"},
            {"title": "AI Risk Flags", "body": "The RiskAgent continuously monitors all projects and surfaces risks with severity ratings. Red = critical, orange = high. Click any flag to see the AI's reasoning.", "icon": "⚠️", "page": "ceo"},
            {"title": "Financial Overview", "body": "See total budget allocated, amount spent, outstanding invoices, and payment status across all projects in your company.", "icon": "💰", "page": "ceo"},
            {"title": "2FA is protecting you", "body": "Your account is secured with two-factor authentication. You need your authenticator app each time you log in. You can manage 2FA in Settings → Security.", "icon": "🔐", "page": "settings"},
            {"title": "Google Calendar sync", "body": "Connect your Google Calendar in Settings → Integrations so platform meetings sync automatically to your calendar.", "icon": "📅", "page": "settings"},
        ],
        "admin": [
            {"title": "Welcome, Admin 👋", "body": "You run day-to-day operations. You can create and manage projects, assign employees, trigger AI agent workflows, and see every AI decision your system makes.", "icon": "⚙️", "page": None},
            {"title": "Projects", "body": "Create a project with a budget, deadline, priority, and client. Then add tasks with required skills — the AI will handle staffing automatically.", "icon": "📁", "page": "projects"},
            {"title": "Team Dashboard", "body": "See all your employees, their skills, current workload, and availability. The AI uses this data to make assignment decisions.", "icon": "👥", "page": "employees"},
            {"title": "Multi-Agent Workbench", "body": "Trigger the full AI pipeline for any project. Seven agents run in sequence: Intake → Planning → Staffing → Risk → Execution → Communication → Escalation.", "icon": "🤖", "page": "multi-agent"},
            {"title": "Agentic Dashboard", "body": "See every decision the AI has made — with confidence scores, reasoning, and input/output data. Full transparency and audit trail.", "icon": "🧠", "page": "decisions"},
            {"title": "Your Profile & Settings", "body": "Set up your profile, connect Google Calendar, configure email notifications, and manage your password in Settings.", "icon": "👤", "page": "settings"},
        ],
        "employee": [
            {"title": "Welcome to your workspace 👋", "body": "The AI assigns tasks to you based on your skills, current workload, and efficiency score. Keep your profile updated to get the best matches.", "icon": "🧑‍💻", "page": None},
            {"title": "My Dashboard", "body": "Your dashboard shows all tasks assigned to you, sorted by urgency. You can see deadlines, required skills, and the project each task belongs to.", "icon": "📋", "page": "dashboard"},
            {"title": "Task Progress", "body": "Click any task to update its progress, add notes, or flag it as blocked. Blocked tasks trigger the AI EscalationAgent automatically.", "icon": "✅", "page": "dashboard"},
            {"title": "My Projects", "body": "See all projects you are involved in, your role on each, and the overall project health and progress.", "icon": "📁", "page": "projects"},
            {"title": "Your Profile & Skills", "body": "Update your skills in Settings → Profile. The AI StaffingAgent uses your skills profile to score task-to-employee fit — higher scores mean better matches.", "icon": "🎯", "page": "settings"},
        ],
        "client": [
            {"title": "Welcome 👋", "body": "This is your project portal. You can see the real-time status of your projects, task progress, and receive updates from the team — all in one place.", "icon": "👁", "page": None},
            {"title": "Project Status", "body": "The Projects page shows all your active projects with progress bars, budget usage, priority, and current status. Click any project to drill in.", "icon": "📊", "page": "projects"},
            {"title": "Task Progress", "body": "Inside each project you can see individual tasks, their completion status, and which team member is working on them.", "icon": "✅", "page": "projects"},
            {"title": "Getting help", "body": "If you need to raise a concern or request a change, use Settings → Support to send a message directly to your team's admin.", "icon": "💬", "page": "settings"},
        ],
    }.get(role, [
        {"title": "Welcome to AI Workforce Orchestrator", "body": "Use the navigation bar to explore your available features.", "icon": "👋", "page": None},
    ])

    return {"role": role, "steps": steps}
